[project]
name = "sltop"
version = "0.2.0"
description = "A top-like queue viewer for Slurm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.2.0",
    "tyro>=1.0.3",
]

[project.scripts]
sltop = "sltop.main:_cli"


[dependency-groups]
dev = [
    "pre-commit>=4.0.0",
    "pyright>=1.1.400",
    "pytest>=8.0.0",
    "ruff>=0.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 80
indent-width = 4

[tool.ruff.lint]
select = [
    "E", "F", "W", "N", "I", "D", "NPY"
]
ignore = [
    "D102",  # Inheriting docstrings is allowed
    "D107",  # Initializer goes in the class docstring
    "D401",  # "Imperative mood" NLP doesn't always make sense
    "D413",  # No blank lines after section is preferred by mkdocstrings
    "E402",  # Module level imports sometimes need to occur after configuration

    # Must pick one...
    "D213",  # Pick 'multi-line-summary-first-line'.
    "D203",  # Pick `no-blank-line-before-class`.
]

[tool.pyright]
include = ["src", "tests"]
pythonVersion = "3.12"
